### ISSUE TITLE
Not support androidX

### ISSUE THREAD

**Issue by xanxusldw** [allure-framework/allure-android#13]
Though add android.enableJetifier=true to build.gradle,  for the Jetifier has some problem with de library migration.  the AllureAndroidListener always implements android.support.test.internal.runner.listener.InstrumentationRunListener, not convert to corresponding androidx's class.  it will run fail to find this class.

**Comment by rasskazovaleksey** [comment]
PR was done into allure-android module, which supports android packages, simple overriding dependencies on the same module should arise inconvenience, androidx and android support should be split into different modules.

**Comment by shrinivaskhawase** [comment]
Hi guys thank you very much for this awesome fix I see that it has been merged to master. Will this be available as a new version soon? Currently its not part of 2.5.1

**Comment by viclovsky** [comment]
Hi, @shrinivaskhawase . New version (BETA) with support AndroidX, available [here](https://bintray.com/qameta/maven/allure-android/2.0.0-beta1).  Please, look at README.md.
