### ISSUE TITLE
How to add it to the project ? 

### ISSUE THREAD

**Issue by azakordonets** [allure-framework/allure-android#2]
Gradle can't resolve dependencies for this library. How could I add it to my project?

**Comment by Badya** [comment]
Right now it is not present on bintray - building jars and aar from source should help

**Comment by azakordonets** [comment]
And then putting it to local repo ? Should i put jar and aar in same place ?

**Comment by Badya** [comment]
local repo is ok. jars and aars should be stored according to it's dependency name `$LOCAL_REPO/ru/tinkoff/allure`
