### ISSUE TITLE
These examples not implemented with the latest version

### ISSUE THREAD

**Issue by moatazeldebsy** [allure-framework/allure-android#27]
these examples not implemented with the latest version

Logcat rule's
You can use LogcatDumpRule, LogcatClearRule to clear and capture a device logs in case of Throwable during test

```
class MyTest {

    @get:Rule
    val ruleChain = RuleChain.outerRule(LogcatClearRule()).around(LogcatDumpRule())

    // ...
}
```
Window hierarchy rule
You can use WindowHierarchyRule to capture a window hierarchy via UIautomator in case of Throwable during test

```
class MyTest {

    @get:Rule
    val windowHierarchyRule = WindowHierarchyRule()

    // ...
}
```

Also these annotations not found :
```
@Owner
@Severity
@Step

```

**Comment by viclovsky** [comment]
I have updated ReadMe. Please, look at it.
