### ISSUE TITLE
Нумерация актуальной версии в релизе и в описании сбивает с толку

### ISSUE THREAD

**Issue by almaz010891** [allure-framework/allure-android#34]
https://github.com/allure-framework/allure-android/releases -  тут самая свежая версия, в которой добавлена поддержка AndroidX и прочие улучшения - имя версии 2.0.0-beta1

В описании содержатся устаревшие зависимости (например, support) + версия 2.5.1

Вопрос - Что случилось с именованием версии, можно ли уже пользоваться новой версией (которая 2.0.0-beta1) и добавлена ли она в репозиторий? Спасибо

**Comment by viclovsky** [comment]
Новой версией можно пользоваться, она в бета тестировании. Я поправил описание. Единственно, что она не совместима с предыдущими версиями.

**Comment by almaz010891** [comment]
Спасибо большое!

вт, 22 окт. 2019 г. в 19:04, Victor Orlovsky <notifications@github.com>:
