### ISSUE TITLE
Improvement. No way to specify the size of the screenshot

### ISSUE THREAD

**Issue by almaz010891** [allure-framework/allure-android#40]
Скриншоты в отчета аллюра визуально занимают много места. 
Было бы неплохо, чтобы для метода 
deviceScreenshot("screenshot_name") и FailshotRule была возможность указывать максимальный размер скриншота в пикселах (например, по длинной стороне). В большинстве случаев оригинальный размер скриншота не нужен. К тому же ужатый скрин значительно меньше занимает места и более органично вписывается в отчет аллюра

**Comment by Badya** [comment]
Не думаю что обрабатывать картинки на девайсах хорошая идея, как минимум повлияет на скорость выполнения тестов.
Выглядит как задача для CI сервера с использованием ImageMagick.
