### ISSUE TITLE
Complete example is missing

### ISSUE THREAD

**Issue by neestell** [allure-framework/allure-android#43]
Please create a sample module to demonstrate how properly the library works.
At this moment I have a problem with taking screenshot method `deviceScreenshot`(app throws an exception `java.io.IOException: open failed: EACCES (Permission denied)).` on any device

**Comment by viclovsky** [comment]
Hi @neestell  
Looak at the example below, please:
https://github.com/allure-framework/allure-android/blob/master/allure-espresso/src/androidTest/kotlin/io/qameta/allure/android/AllureTest.kt

It is complex example for some popular allure-android usecases.

**Comment by neestell** [comment]
Ok thanks!
