### ISSUE TITLE
Improvement. Add custom labels and links feature

### ISSUE THREAD

**Issue by Silencegod** [allure-framework/allure-android#45]
I need to have availability to easily create custom labels/links and use AllureId annotation to integrate with Allure Enterprise.
It implemented in allure-java by LabelAnnotation and LinkAnnotation.
This kind of feature can be useful in allure-android too.

**Comment by Anton22Shkredov** [comment]
It will be great improvement, we are using Allure EE as well and need to link results with test-cases there.
