### ISSUE TITLE
Report is not generate when application crashed

### ISSUE THREAD

**Issue by Silencegod** [allure-framework/allure-android#49]
An allure report will not be generated in case of application crash while executing test.
You can wrap tests from allure-espresso module (CrashTest and RXCrashTest) with step() method to reproduce the same behaviour.
The expected result is report with all failed tests even if application has crashed.

**Comment by ccarpita** [comment]
I'm experiencing the same issue, and wondering what the best course of action is. Thanks!

**Comment by viclovsky** [comment]
Hi, all. Thanks a lot for bug report. Currently we are working hard on new version of [allure-android](https://github.com/allure-framework/allure-kotlin) and every effort is made on pushing it in production.
