### ISSUE TITLE
Генерация retries в allure отчете

### ISSUE THREAD

**Issue by davidbugayov** [allure-framework/allure-android#7]
Планирует ли вы добавлять поддержку retry для отчета allure ?

**Comment by viclovsky** [comment]
Привет, @davidbugayov . Да, планируем. Я сообщу, когда появится поддержка.

**Comment by davidbugayov** [comment]
> Привет, @davidbugayov . Да, планируем. Я сообщу, когда появится поддержка.

Да, я уже сделал, можете у меня в форке посмотреть
